---
title: "Phenotyping_script2"
author: "Veronica"
date: "6/13/2017"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plyr)
library(tidyverse)
library(reshape2)
library(lmerTest)
library(lme4)
```

## Final Phenotyping Data

### Load Data  
```{r}
(raw.flower <- read_csv("ELF3_flowering.csv", locale = locale(date_format = "%d/%m/%Y")))
 
(flower <- raw.flower %>%
  filter(ugly == FALSE) %>% 
  mutate(
    days.g2p = parse_integer(petals - germ),
    days.p2a = parse_integer(anthesis - petals),
    days.a2f = parse_integer(final - anthesis),
    days.g2a = parse_integer(anthesis - germ),
    days.g2f = parse_integer(final - germ), 
    leaf_node = leaves / internodes))

flower$genotype <- factor(flower$genotype, levels = c("GV_WT", "ELF3_mutant"))
```

### Flowering Time  
```{r}
flower %>%
  ggplot(aes(genotype, days.g2p)) +
  geom_boxplot() +
  ggtitle("DAS to petal emergence") + 
  xlab("Genotype") + 
  ylab("Days") +
  theme(plot.title = element_text(hjust = .5)) 
summary(lmer(days.g2p ~ genotype + (1|germ), data=flower))

flower %>%
  ggplot(aes(genotype, days.p2a)) +
  geom_boxplot() +
  ggtitle("Days from petal emergence to anthesis") + 
  xlab("Genotype") + 
  ylab("Days") +
  theme(plot.title = element_text(hjust = .5)) 
summary(lmer(days.p2a ~ genotype + (1|germ), data=flower))

flower %>%
  ggplot(aes(genotype, days.a2f)) +
  geom_boxplot() +
  ggtitle("Duration of anthesis") + 
  xlab("Genotype") + 
  ylab("Days") +
  theme(plot.title = element_text(hjust = .5)) 
summary(lmer(days.a2f ~ genotype + (1|germ), data=flower))

flower %>%
  ggplot(aes(genotype, days.g2a)) +
  geom_boxplot() +
  ggtitle("DAS to anthesis") + 
  xlab("Genotype") + 
  ylab("Days") +
  theme(plot.title = element_text(hjust = .5)) 
summary(lmer(days.g2a ~ genotype + (1|germ), data=flower))

flower %>%
  ggplot(aes(genotype, days.g2f)) +
  geom_boxplot() +
  ggtitle("DAS to end of anthesis") + 
  xlab("Genotype") + 
  ylab("Days") +
  theme(plot.title = element_text(hjust = .5)) 
summary(lmer(days.g2f ~ genotype + (1|germ), data=flower))
```

### Head, Height, Leaves  
```{r}
flower %>%
  ggplot(aes(genotype, Head_diameter)) +
  geom_boxplot() +
  ggtitle("Head diameter") + 
  xlab("Genotype") + 
  ylab("Diameter (cm)") +
  theme(plot.title = element_text(hjust = .5)) 
summary(lmer(Head_diameter ~ genotype + (1|germ), data=flower))

flower %>%
  ggplot(aes(genotype, final_height)) +
  geom_boxplot() +
  ggtitle("Mature height") + 
  xlab("Genotype") + 
  ylab("Height (cm)") +
  theme(plot.title = element_text(hjust = .5)) 
summary(lmer(final_height ~ genotype + (1|germ), data=flower))

flower %>%
  ggplot(aes(genotype, internodes)) +
  geom_boxplot() +
  ggtitle("Number of internodes") + 
  xlab("Genotype") + 
  ylab("Number") +
  theme(plot.title = element_text(hjust = .5)) 
summary(lmer(internodes ~ genotype + (1|germ), data=flower))

flower %>%
  ggplot(aes(genotype, leaves, color = genotype)) +
  geom_boxplot() +
  ggtitle("Number of leaves") + 
  xlab("Genotype") + 
  ylab("Number") +
  theme(plot.title = element_text(hjust = .5)) 
summary(lmer(leaves ~ genotype + (1|germ), data=flower))

flower %>%
  ggplot(aes(genotype, leaf_node)) +
  geom_boxplot() +
  ggtitle("Leaves per internodes") + 
  xlab("Genotype") + 
  ylab("Number leaves:Number internodes") +
  theme(plot.title = element_text(hjust = .5)) 
summary(lmer(leaf_node ~ genotype + (1|germ), data=flower))
```

### Stem circumfrence  
```{r}
flower %>%
  ggplot(aes(genotype, stem_circ_1)) +
  geom_boxplot() +
  ggtitle("Stem circumfrence, internode 1") + 
  xlab("Genotype") + 
  ylab("Circumfrence (cm)") +
  theme(plot.title = element_text(hjust = .5)) 
summary(lmer(stem_circ_1 ~ genotype + (1|germ), data=flower))

flower %>%
  ggplot(aes(genotype, stem_circ_2)) +
  geom_boxplot() +
  ggtitle("Stem circumfrence, internode 2") + 
  xlab("Genotype") + 
  ylab("Circumfrence (cm)") +
  theme(plot.title = element_text(hjust = .5)) 
summary(lmer(stem_circ_2 ~ genotype + (1|germ), data=flower))

flower %>%
  ggplot(aes(genotype, stem_circ_3)) +
  geom_boxplot() +
  ggtitle("Stem circumfrence, mid-stem") + 
  xlab("Genotype") + 
  ylab("Circumfrence (cm)") +
  theme(plot.title = element_text(hjust = .5)) 
summary(lmer(stem_circ_3 ~ genotype + (1|germ), data=flower))

flower %>%
  ggplot(aes(genotype, stem_circ_4)) + 
  geom_boxplot() +
  ggtitle("Stem Circumfrence, below infloresence") + 
  xlab("Genotype") + 
  ylab("Circumfrence (cm)") +
  theme(plot.title = element_text(hjust = .5)) 
summary(lmer(stem_circ_4 ~ genotype + (1|germ), data=flower))
```

